### ISSUE TITLE
Stuck at getting current progress.

### ISSUE THREAD

**Issue by culloa1** [Zaarrg/TTVDropBot#10]
I tried reinstalling and running as admin but it’s stuck at current progress. I opened chrome to
Watch the streamer and made sure progress was being counted but on the app its stuck.

**Comment by Zaarrg** [comment]
This issue is mostly network based, noticed that when the twitch progress page didn't load the drops in. Should be better in [1.3.3](https://github.com/Zaarrg/TTVDropBot/releases) because it now reloads the page more often to make sure everything is loaded but can still happen that something does not load which the bot is waiting for and therefor will be stuck at waiting for something that isn't there.
