### ISSUE TITLE
Switches streams after 3 fails, even if not 3 in a row

### ISSUE THREAD

**Issue by Reserton** [Zaarrg/TTVDropBot#18]
The program seems to switch streams after 3 failures. It seems to get a failure to check every 3-5 attempts. This eventually causes it to switch streams even when the stream is still up.

In my opinion it should only switch if it is " 3 failures in a row" not  "3 failures total"

I assume resetting the try count on a successful check, would be a quick way to fix this.

![image](https://user-images.githubusercontent.com/1967737/126049761-81f8cf59-f271-488d-8712-03c0217ed36e.png)

To add a suggestion to this. it would be useful to be able to add a list of streamers I already have drops for so it does not check them anymore. As it takes a long time to get 3 trys on a stream I already have the drop for.

Possibly automatically log streams the tool has got 100% for or detected 100% for too.

**Comment by Zaarrg** [comment]
I think most of it i adressed in the 1.3.3 release.

- The Bot now checks if the Drops is already claimed so this should prevent the Bot from waitng a long time for 3 retries.
- Also lowered the time between retries to 2.5 minutes instead of 4 minutes each.

And to reset the try counter on a successfull try will be added, sadly read this after the 1.3.3 release so will have to add it to another release. Never thought about what would happen if the Bot gets a retry then a percentage and then a retry. So thanks for finding this issue.

**Comment by Zaarrg** [comment]
Retry fix was added at the latest [comit](https://github.com/Zaarrg/TTVDropBot/commit/615a5f55458299a80bc301236d74d4543921182d). Thnx for the retry fix by @BoTeQX.
