### ISSUE TITLE
1.3.3 gives me all live channels claimed, but they are not

### ISSUE THREAD

**Issue by TrapStoner** [Zaarrg/TTVDropBot#21]
I just updated to 1.3.3 and opened it to continue watching Sykkuno (had 12%) and after selecting him the bot gives me All live channels claimed... Almost... All but sykkuno's drop are claimed. Maybe it can't differentiate from sykkuno's old drop (that i have indeed claimed) and his new drop (that is at 12%). [Check the photo](https://prnt.sc/1cehg9a)

**Comment by TrapStoner** [comment]
Also forgot to say thanks for the update and all the work on it it's amazing!

**Comment by Pwnyhof** [comment]
I have the exact same problem @TrapStoner has, I'm missing Sykkuno-97% but the bot says it's already claimed.

**Comment by Zaarrg** [comment]
Okay finally recreated the error the bot acutally thinks that xQc Assault Rifle is Sykkuno Assault Rifle because its so similar, will have to fix it tomorrow as it already 4 a.m. 

**For now use one of those fixes:**
-The Check if the Drop is claimed is disabled, will add the feature after i fixed it.
- If using node:
Just Clone the repo and get the new version
- If using exe:
Download and replaced your ttvdropbot.exe with the one out of the TTVDropBot Temporarily Fixed.zip.
[TTVDropBot Temporarily Fixed.zip](https://github.com/Zaarrg/TTVDropBot/files/6835563/TTVDropBot.Temporarily.Fixed.zip)

**Comment by Zaarrg** [comment]
Bot now should correctly recognize the claimed drops. Fixed by the release of [1.3.3.1](https://github.com/Zaarrg/TTVDropBot/releases/tag/1.3.3.1)
