### ISSUE TITLE
bot closing with error

### ISSUE THREAD

**Issue by iAnvar** [Zaarrg/TTVDropBot#50]
I don’t know why but sometimes bot automatically closing with these error

![865A59B5-EC50-433D-BAF5-44C7B8D8578F](https://user-images.githubusercontent.com/84909834/163736665-163f9006-bf73-48f3-b39f-01e0deae41da.png)

**Comment by daeeros** [comment]
++ i have same problem

**Comment by Zaarrg** [comment]
Should be fixed with the latest [commit](https://github.com/Zaarrg/TTVDropBot/commit/c77c9af4141860232faca561553a514b3157a9c4) otherwise just reopen this issue, you can download the latest compiled commit in the [package ](https://github.com/Zaarrg/TTVDropBot/tree/main/package)folder of the repo. 
https://github.com/Zaarrg/TTVDropBot/tree/main/package
