### ISSUE TITLE
Compiled Files Placed in Master - Cloning Slow

### ISSUE THREAD

**Issue by hifocus** [Zaarrg/TTVDropBot#52]
Currently the compiled files are placed under the `package` directory, and each took up >50MB of size. The whole repo was 476.65 MiB making cloning the repo under low bandwidth environment slow.

```
root@instance-prod:~# git clone https://github.com/Zaarrg/TTVDropBot
Cloning into 'TTVDropBot'...
remote: Enumerating objects: 906, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 906 (delta 16), reused 51 (delta 16), pack-reused 855
Receiving objects: 100% (906/906), 476.65 MiB | 12.04 MiB/s, done.
Resolving deltas: 100% (535/535), done.
Updating files: 100% (44/44), done.
```

Consider moving the compiled files to a separate branch or use Release. You can always do pre-releases and alpha versions.

**Comment by Zaarrg** [comment]
Moved packages folder from [main branch](https://github.com/Zaarrg/TTVDropBot/tree/main) to [build branch](https://github.com/Zaarrg/TTVDropBot/tree/build) reducing main branches size a bit ~100 mb

You are getting ~470 mb because thats the size of all branches together and git fetches every branch while cloning.
To prevent this you have to add `--single-branch` to only clone one branch, in this case the default one. 
Use `git clone --single-branch https://github.com/Zaarrg/TTVDropBot` to achive this.
This gets me to ~270 mb.

![grafik](https://user-images.githubusercontent.com/62082797/164763004-8b446487-68ed-44c4-960c-420a81ff9f83.png)
